//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        public int IDJugador { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Posicion { get; set; }
        public int IDEquipo { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
