//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class DiplomadoCurneDBEntities : DbContext
    {
        public DiplomadoCurneDBEntities()
            : base("name=DiplomadoCurneDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Jugadores> Jugadores1 { get; set; }
    }
}
